### ISSUE TITLE
Permission denied: '/data/couchpotato/logs'

### ISSUE THREAD

**Issue by deanpcmad** [dylanlindgren/docker-couchpotato#2]
Hey there, I'm trying to use this Docker image but I'm having issues.
I'm getting these errors when trying to run the docker container:

```bash
root@server:~# docker run --rm --name couchpotato -p 5050:5050 -v /tmp/couchpotato:/data/couchpotato:rw dylanlindgren/docker-couchpotato
Traceback (most recent call last):
  File "/var/lib/CouchPotatoServer/CouchPotato.py", line 131, in <module>
    l = Loader()
  File "/var/lib/CouchPotatoServer/CouchPotato.py", line 57, in __init__
    os.makedirs(self.log_dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/data/couchpotato/logs'

Traceback (most recent call last):
  File "/var/lib/CouchPotatoServer/CouchPotato.py", line 131, in <module>
    l = Loader()
  File "/var/lib/CouchPotatoServer/CouchPotato.py", line 57, in __init__
    os.makedirs(self.log_dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/data/couchpotato/logs'
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
sed: can't read /data/couchpotato/settings.conf: No such file or directory
Traceback (most recent call last):
  File "/var/lib/CouchPotatoServer/CouchPotato.py", line 131, in <module>
    l = Loader()
  File "/var/lib/CouchPotatoServer/CouchPotato.py", line 57, in __init__
    os.makedirs(self.log_dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/data/couchpotato/logs'

Traceback (most recent call last):
  File "/var/lib/CouchPotatoServer/CouchPotato.py", line 131, in <module>
    l = Loader()
  File "/var/lib/CouchPotatoServer/CouchPotato.py", line 57, in __init__
    os.makedirs(self.log_dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/data/couchpotato/logs'
```

I've tried changing the directory & also tried running under different users.

When I create the logs folder I then get this error: 

```
IOError: [Errno 13] Permission denied: '/data/couchpotato/logs/error.log'
```

Any ideas?

**Comment by dylanlindgren** [comment]
Hey Dean,

Just make sure the user `couchpotato` that's actually running the application within the container has write access to the `/data/couchpotato` directory within the container.

As it's a directory on your host that's being mapped within the container, you will need to set these permissions on the host. You can do it simply by running chmod on your `/tmp/couchpotato` directory on your host as follows:

`sudo chmod -R 777 /tmp/couchpotato`

After doing that you shouldn't have any errors, although it's not particularly secure.

Hope this helps.

**Comment by dylanlindgren** [comment]
Hey Dean.

I just responded to your issue on Github. See below:
https://github.com/dylanlindgren/docker-couchpotato/issues/2

Kind regards,

Dylan
